### PR TITLE
Recommend latest libyui-qt7, not obsolete libyui-qt5 in .spec

### PR DESCRIPTION
**Pull request by shundhammer**

### CODE REVIEW

**Comment by imobach** [comment]
LGTM

**Comment by lslezak** [comment]
Please add bug number `bsc#952249` to the changes (and close https://bugzilla.suse.com/show_bug.cgi?id=952249).

**Comment by imobach** [comment]
Uh, I overlooked it!

**Comment by shundhammer** [comment]
Added bug number.

**Pull request merged**
