### PR TITLE
Fixes for %_libexecdir changing to /usr/libexec

### LINKED ISSUE #47: Libexecdir move breaks package
%{_libexecdir} will be moving to /usr/libexec because of FHS 3.0. /usr/lib/YaST2/bin/y2controlcenter is affected

### PR DESCRIPTION
**Pull request by gmbr3**
* Fixes for %_libexecdir changing to /usr/libexec

close #47

### CODE REVIEW

**Comment by gmbr3** [comment]
Closes #47

**Comment by dgdavid** [comment]
I guess this is because

> openSUSE Factory is in the process of changing <code>%_libexecdir</code> to <code>/usr/libexec</code> to match [Filesystem Hierarchy Standard](https://wiki.linuxfoundation.org/lsb/fhs) 3.0. Any packages which require a macro for <code>/usr/lib</code> are being changed to use <code>%_prefix/lib</code>. openSUSE Leap 15.2 will still expand <code>%_libexecdir</code> to <code>/usr/lib</code>  

https://en.opensuse.org/openSUSE:Specfile_guidelines#Libexecdir

**Comment by gmbr3** [comment]
Yeah, it is.

**Comment by gmbr3** [comment]
@DimStar77 #48

**Pull request closed without merging**
