### PR TITLE
Use 128x128 sized icon in X11.

### PR DESCRIPTION
**Pull request by xuzhao9**
This PR will fix this bug:https://bugzilla.opensuse.org/show_bug.cgi?id=1030988

### CODE REVIEW

**Comment by jreidinger** [comment]
Can you please a bit explain why you think it will fix that bug?

**Comment by xuzhao9** [comment]
@jreidinger YaST will load /usr/share/pixmap/yast.png as the X11 window icon. This patch will increase the png file resolution to 128x128, which will fix the icon blurred bug in the link. (I am also the reporter of the bug 1030988.)

**Comment by jreidinger** [comment]
@xuzhao9 ok, but bug also mention that we use 256x256, why do not use it?

**Comment by xuzhao9** [comment]
This is because the list of icon sizes (128x128, 64x64, 32x32 and 16x16) has been in Qt since Qt 5.0 (2012,) so it's probably stable. I'd hope if DEs want bigger icons, they'd try the ones in /usr/share/icons instead.

**Comment by jreidinger** [comment]
@xuzhao9 ok, so please increase version and add entry to changelog and I can merge it. Just be aware to increase version to `3.2.0` as we dump minor recently. Thanks

**Comment by xuzhao9** [comment]
@jreidinger I have done that as required.

**Comment by jreidinger** [comment]
@xuzhao9 I miss there increase of version in spec file. otherwise it looks good

**Comment by xuzhao9** [comment]
@jreidinger Right. Just fixed this bug and committed.

**Pull request merged**
